// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.TreasuryYields
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("date")]
        public DateTimeOffset? Date { get; set; }

        [JsonProperty("bills")]
        public double? Bills { get; set; }

        [JsonProperty("notes")]
        public double? Notes { get; set; }

        [JsonProperty("bonds")]
        public double? Bonds { get; set; }

        [JsonProperty("tips")]
        public double? Tips { get; set; }

        [JsonProperty("frn")]
        public double? Frn { get; set; }

        [JsonProperty("changes")]
        public Changes Changes { get; set; }

        [JsonProperty("previousDate")]
        public DateTimeOffset? PreviousDate { get; set; }
    }

    public partial class Changes
    {
        [JsonProperty("bills")]
        public Bills Bills { get; set; }

        [JsonProperty("notes")]
        public Bills Notes { get; set; }

        [JsonProperty("bonds")]
        public Bills Bonds { get; set; }

        [JsonProperty("tips")]
        public Bills Tips { get; set; }

        [JsonProperty("frn")]
        public Bills Frn { get; set; }
    }

    public partial class Bills
    {
        [JsonProperty("change1d")]
        public double? Change1D { get; set; }

        [JsonProperty("direction")]
        public string Direction { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
