// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.TreasuryYields
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("date")]
        public DateTimeOffset Date { get; set; }

        [JsonProperty("bills")]
        public double Bills { get; set; }

        [JsonProperty("notes")]
        public double Notes { get; set; }

        [JsonProperty("bonds")]
        public double Bonds { get; set; }

        [JsonProperty("tips")]
        public double Tips { get; set; }

        [JsonProperty("frn")]
        public double Frn { get; set; }
    }
}
